### PR TITLE
feat(cache): use sqlite to store translation cache

### PR DESCRIPTION
**Pull request by awwaawwa**
- [x] Implement database-related operations
- [x] Modify `translator.py`, have `BaseTranslator` handle cache matters
- [x] Add relevant tests

In addition, I modified the Test and Build Python Package Action to be triggered by any branch.

### CODE REVIEW

**Comment by awwaawwa** [comment]
For the issue described in https://github.com/Byaidu/PDFMathTranslate/issues/214, I have included both the translation engine and its parameters in the cache, and only when the engine, parameters, and original text are all identical, the cache is returned. However, parameters affecting the translation results need to be manually maintained in the `translator.py` file.

**Comment by awwaawwa** [comment]
I tested `OpenAITranslator` locally, and it can cache correctly. The other translation engines have not been tested individually, but they should be fine.

**Comment by awwaawwa** [comment]
I haven't written the `ignore_cache` CLI argument and web UI parameter. If anyone is interested in writing it, I hope it can be added after https://github.com/Byaidu/PDFMathTranslate/pull/329 is merged. Thank you very much.

**Comment by Byaidu** [comment]
Thanks for contribution!

**Pull request merged**
